### ISSUE TITLE
Requirements for Photos

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex_native#1]
1. Splash screen
2. App icon - 512 x 512 px
3. Banner for playstore - 1024 x 500 px

**Comment by saiabhijitht** [comment]
<details>
<summary>Splash screen sample</summary>

<img width="961" alt="learn cards1" src="https://user-images.githubusercontent.com/23223985/33884054-39866e22-df64-11e7-9b70-02e1093e1e9f.png">
</details>
<details>
<summary>Splash screen text</summary>

<img width="961" alt="learn cards1" src="https://user-images.githubusercontent.com/23223985/33884056-39c830a0-df64-11e7-82a1-95ba128082b5.png">
</details><details>
<summary>App Icon</summary>

<img width="961" alt="learn cards1" src="https://user-images.githubusercontent.com/23223985/33884058-3a0cb86a-df64-11e7-9949-db945fc7e2ee.png">
</details><details>
<summary>Banner 1024X500</summary>

<img width="961" alt="learn cards1" src="https://user-images.githubusercontent.com/23223985/33884060-3a4f9996-df64-11e7-8171-a50409c9677a.png">
</details>

<details>
<summary>Splash screen logo</summary>


<img width="961" alt="learn cards1" src="https://user-images.githubusercontent.com/23223985/33884061-3a925ace-df64-11e7-84cb-04fb3b8f3b2f.png">
</details>

**Comment by mallelapavank** [comment]
Thanks. I had the same design in mind for the splash screen. Wondering if there should be a loading indicator at the bottom of splash screen

**Comment by M-ZubairAhmed** [comment]
When asked about loading bar @saiabhijitht had the opinion that people don't like loading bar on splash screen

**Comment by M-ZubairAhmed** [comment]
what do you think

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed I actually did not mean to not have loading bar. I just did not want it the traditional way of circular dots or bar. I gave a try to do something else, but I understood I lost a bit of grip on aftereffects. If you have got some more time, myself or any contributor can give it another try. If you are sure the loading takes a bit of time, like more than 5 secs, we should do it better.

**Comment by mallelapavank** [comment]
@saiabhijitht loading time is unpredictable since we are fetching the actual mobile site. Totally depends on internet connectivity and speed.

**Comment by mallelapavank** [comment]
While testing on my device it takes about 3-4 seconds on wifi and anywhere between 5 to 10 seconds on 4g. Without the loading indicator the app might look dead for a while. I will add the default loading view of react native for now. The view will be circular for android and circular dots for ios. Can add custom icons later.

**Comment by M-ZubairAhmed** [comment]
that sounds good to me

**Comment by duttakapil** [comment]
What's the progress on the app? To be able to apply for the challenge, we should have it in play store by 18th at the least.

**Comment by mallelapavank** [comment]
working on splash screen. app is ready otherwise.
