### ISSUE TITLE
Publishing the app on Play Store

### ISSUE THREAD

**Issue by mallelapavank** [coderplex/coderplex_native#2]
1. Need to setup Google Play Store account by making a $25 one time payment. 
2. When setting up add me as a developer to the account.
3. Send me a short description (80 characters) and full description (4000 characters) about the app.
4. Logo and banner images are ready. Send a promo video link if we have one.
5. We have to select a category that best fits our app from the given list. I think we fit in Education.

Usually Google's review process would be around 2 hours for every upload.

**Comment by duttakapil** [comment]
> Need to setup Google Play Store account by making a $25 one time payment.

@M-ZubairAhmed was saying that we can use his Play Store account. Do you suggest that we create official Coderplex account?

**Comment by mallelapavank** [comment]
IMO its good to create official account. Transferring an app from one account to another is a process.
https://support.google.com/googleplay/android-developer/answer/6230247?hl=en

**Comment by duttakapil** [comment]
Where do you setup the Play Store account?

**Comment by M-ZubairAhmed** [comment]
https://support.google.com/googleplay/android-developer/answer/6112435?hl=en&visit_id=1-636491572425926986-3698540464&rd=1

**Comment by mallelapavank** [comment]
Correct. The link @M-ZubairAhmed gave has all the necessary information about the process of setting up Play Store account. Here's the direct signup link.
https://play.google.com/apps/publish/signup/

1. Signin with your Google account
2. Pay registration fee
3. Follow on screen instructions. And you're done.

**Comment by duttakapil** [comment]
@M-ZubairAhmed we can go ahead with using your Play Store account to publish the app. We'll create a official Coderplex account once we have our official bank account ready

**Comment by mallelapavank** [comment]
Created a release tag and uploaded the apk. @M-ZubairAhmed do you want to deploy it to playstore?

**Comment by M-ZubairAhmed** [comment]
Yes I want to but I haven't done before anytime. How should I be giving
access to you ?

**Comment by mallelapavank** [comment]
Done publishing the app on play store using @M-ZubairAhmed account. 
I deployed it to alpha channel. It's under review now. Google will generate a test report shortly. And then I will move it to beta.

**Comment by M-ZubairAhmed** [comment]
Awesome 💯 🎆 🍾  thank you @mallelapavank, Please post the link here once its available

**Comment by M-ZubairAhmed** [comment]
https://play.google.com/store/apps/details?id=org.coderplex
